Vagrant.configure("2") do |config|
  config.vm.box = "concourse/lite"
  config.vm.box_version = "2.6.0.pre.rc.3"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end
end
